Be specific about which dependency is not met.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -70,13 +70,16 @@ lib_ldflags() {
 
 # Check required dependencies
 DEPS="libswscale x264"
-if lib_present "$DEPS"; then
-    CXXFLAGS+=$(lib_cflags $DEPS)
-    LDFLAGS+=$(lib_ldflags $DEPS)
-else
-    echo 2>&1 "error: missing one of the required dependencies ($DEPS)"
-    exit 1
-fi
+for DEP in $DEPS
+do
+    if lib_present "$DEP"; then
+        CXXFLAGS+=$(lib_cflags $DEP)
+        LDFLAGS+=$(lib_ldflags $DEP)
+    else
+        echo 2>&1 "error: missing one of the required dependencies ($DEP)"
+        exit 1
+    fi
+done
 
 # Check if the ffmpeg version is recent enough.
 cat >$TMPDIR/test.cpp <<EOF
@@ -114,15 +117,19 @@ fi
 
 # Build demos only if we have the required libs installed
 DEMOS_DEPS="gl glu glew sdl"
+LDFLAGS_DEMOS=
 if [ x"$DEMOS" = x"y" ]; then
-    if lib_present $DEMOS_DEPS; then
-        CXXFLAGS+=$(lib_cflags $DEMOS_DEPS)
-        LDFLAGS_DEMOS=$(lib_ldflags $DEMOS_DEPS)
-    else
-        echo 2>&1 "error: demos cannot be built because one of the dependencies ($DEMOS_DEPS) could not be found"
+    for DEMOS_DEP in $DEMOS_DEPS
+    do
+        if lib_present $DEMOS_DEP; then
+            CXXFLAGS+=$(lib_cflags $DEMOS_DEP)
+            LDFLAGS_DEMOS+=$(lib_ldflags $DEMOS_DEP)
+        else
+           echo 2>&1 "error: demos cannot be built because one of the dependencies ($DEMOS_DEP) could not be found"
         echo 2>&1 "error: demos build can be disabled with --disable-demos"
         exit 1
-    fi
+        fi
+    done
 fi
 
 # Show a summary to the user
